apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-guesser
  labels:
    app: number-guesser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: number-guesser
  template:
    metadata:
      labels:
        app: number-guesser
    spec:
      containers:
        - name: number-guesser
          image: foddav/guess-the-number:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
